name: onCreateTag Actions
run-name: Build image and update manifest 🚀
on:
  workflow_run:
    workflows:
      - "onPushToMaster Actions"
    types:
      - "completed"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          path: main

      - name: Get Package version
        run: echo VERSION=$(cat main/package.json | jq -r '.version') >> $GITHUB_ENV

      - name: Get Package name
        run: echo APP=$(cat main/package.json | jq -r '.name') >> $GITHUB_ENV

      - name: Login to Google Artifact Registry
        uses: docker/login-action@v2
        with:
          registry: "${{ vars.GAR_LOCATION }}-docker.pkg.dev"
          username: _json_key
          password: ${{ secrets.GAR_JSON_KEY }}

      - name: Build the Docker image
        run: |
          cd main
          docker build . --file Dockerfile --tag ${{ github.repository }}:${{ env.VERSION }}

      - name: Push to Google Artifact Registry
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: "${{ vars.GAR_LOCATION }}-docker.pkg.dev/${{ vars.GCP_PROJECT_ID }}/${{ vars.GAR_REPOSITORY }}/${{ env.APP }}:${{ env.VERSION }}"

      - name: Clone the Infra repo
        uses: actions/checkout@v3
        with:
          repository: ${{ vars.GIT_INFRA_REPOSITORY }}
          path: infra
          ref: main

      - name: Update the manifest
        run: yq '.image.tag = "${{ env.VERSION }}"' -i infra/${{ env.APP }}/values.yaml

      - name: Push the manifest to infra repository
        run: |
          cd infra
          git config --unset-all http.https://github.com/.extraheader
          git config --global user.email "releaseit@flts.eu"
          git config --global user.name "Release Workflow"
          git add -A
          git commit -am "chore: Bump ${{ env.APP }} version to ${{ env.VERSION }}"
          git push --prune https://token:${{ secrets.INFRA_GH_TOKEN }}@github.com/${{ vars.GIT_INFRA_REPOSITORY }}.git

      - name: This is the end
        run: echo "Uncle Ben's"
